team_finder/team_finder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('match/', include('tinder.urls')),
    path('', views.homepage, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

team_finder/tinder/urls.py
from django.urls import path
from . import views

app_name = 'tinder'
urlpatterns = [
    # path('ola', views.match_withlist, name='match'),
    path('my_menu/', views.my_menu, name='main_menu'),
    path('group/create/', views.create_group, name='create_group'),
    path('group/<int:group_id>/edit/', views.edit_group, name='edit_group'),
    path('group/<int:pk>/', views.DetailGroup.as_view(), name='detail_group'),
    path('group/<int:pk>/delete/', views.DeleteGroup.as_view(), name='delete_group'),
    path('group/<int:pk>/activity/', views.activity_group_match, name='activity-group'),
    path('group/<int:group_id>/match/', views.match_withlist, name='match'),
    path('group/<int:group_id>/join/', views.join_group, name='join_group'),
    path('group/search/', views.search_group, name='search_group'),
]

team_finder/tinder/models/base.py
from django.db import models

class BaseModel(models.Model):

	class Meta():
		abstract = True
		app_label = 'tinder'

team_finder/team_finder/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'core/home.html')

team_finder/team_finder/templates/core/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
    <meta name="description" content="Team Finder">

	<title>{{ page_title }}</title>

    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

	{% block head_extra %}
	{% endblock head_extra %}
</head>
<body>
	{% block header %}
		<header>
            <h1><a href="{% url 'home' %}">Team Finder</a></h1>
			<nav>
                <ul>
                    {% if user.is_authenticated %}
                        {% if user.first_name %}
                            <li><a href="{% url 'tinder:search_group' %}">Buscar por grupo</a></li>
                            <li><a href="{% url 'tinder:main_menu' %}">Meu Espaço</a></li>
                        {% endif %}
                        <li><a href="{% url 'logout' %}">Sair</a></li>
                    {% else %}
                        <li class="login"><a href="{% url 'login' %}">Login</a></li>
                        <li class="register"><a href="{% url 'register' %}">Cadastre-se!</a></li>
                    {% endif %}
                </ul>
			</nav>
		</header>
	{% endblock header %}

	{% block main %}
		<main class="container row">
			{% block main_content %}
			{% endblock main_content %}
		</main>
	{% endblock main %}

	{% block footer %}
		<footer class="container">
            <p>&copy; Diego Cardoso Nunes, Luís Eduardo dos Reis Borges</p>
            <p>Site desenvolvido para a disciplina Desenvolvimento de Aplicações WEB III</p>
        </footer>
	{% endblock footer %}
	{% block end_scripts %}
	{% endblock end_scripts %}
</body>
</html>

team_finder/team_finder/templates/core/home.html
{% extends 'core/base.html' %}


{% block main_content %}

{% endblock main_content %}

team_finder/team_finder/templates/core/toast_messages.html
<script>
    {% if messages %}
        $(() => {
            {% for message in messages %}M.toast({html: "{{ message }}", classes: {% with message.tags as tags %}{% if 'warning' in tags %}"amber darken-2 {% elif 'success' in tags %}"green {% elif 'error' in tags %}"red {% elif 'info' in tags %}"blue {% endif %}{{ message.tags }}"});{% endwith %}{% endfor %}
        });
    {% endif %}
</script>