team_finder/team_finder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from . import views, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('match/', include('tinder.urls')),
    path('', views.homepage, name="home"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

team_finder/tinder/urls.py
from django.urls import path
from . import views

app_name = 'tinder'
urlpatterns = [
    # path('ola', views.match_withlist, name='match'),
    path('my_menu/', views.my_menu, name='main_menu'),
    path('group/create/', views.create_group, name='create_group'),
    path('group/<int:group_id>/edit/', views.edit_group, name='edit_group'),
    path('group/<int:pk>/', views.DetailGroup.as_view(), name='detail_group'),
    path('group/<int:pk>/delete/', views.DeleteGroup.as_view(), name='delete_group'),
    path('group/<int:pk>/activity/', views.activity_group_match, name='activity-group'),
    path('group/<int:group_id>/match/', views.match_withlist, name='match'),
    path('group/<int:group_id>/join/', views.join_group, name='join_group'),
    path('group/search/', views.search_group, name='search_group'),
]

team_finder/tinder/models/base.py
from django.db import models

class BaseModel(models.Model):

	class Meta():
		abstract = True
		app_label = 'tinder'

team_finder/tinder/models/groups.py
from tinder.models.base import *
from django.utils import timezone

class Group(BaseModel):
	"""docstring for Group"""
	name = models.CharField(max_length=100)
	foundation = models.DateField(auto_now_add=True)
	members = models.ManyToManyField('accounts.Profile', related_name='group_list')
	leader = models.ForeignKey('accounts.Profile', related_name='leading', on_delete=models.SET_NULL, null=True)
	private = models.BooleanField(default=False, help_text='Is this group hidden from others?')
	password = models.CharField(max_length=30, blank=True)

	def get_number_of_members(self):
		return len(self.members.all()) + 1

	def __str__(self):
		return("{} -({})".format(self.name, self.foundation))

team_finder/tinder/models/skill_levels.py
from tinder.models.base import *

#Skill_Level is serving as through to user and skills
class SkillLevel(BaseModel):
	SKLEVEL = [
		(1, "Ameba"),
		(2, "Vegetal"),
		(3, "Ser Pensante"),
		(4, "Malandrão"),
		(5, "Topzera"),
	]

	profile = models.ForeignKey('accounts.Profile', on_delete=models.CASCADE)
	skill = models.ForeignKey('Skill', related_name='levels', on_delete=models.CASCADE)
	level = models.IntegerField(choices=SKLEVEL, default=1)

	def __str__(self):
		return("{} (LVL.{}) - Profile: {}".format(self.profile, self.skill, self.level))

team_finder/tinder/models/skills.py
from tinder.models.base import *

class Skill(models.Model):
	KNAREA = [
		("P","Physical Aptitude"),
		("A","Artistic Skill"),
		("B","Biological Science"),
		("H","Human Science"),
		("E","Exact Science"),
		("S","Social Skill"),
	]
	name = models.CharField(max_length=200)
	area = models.CharField(max_length=1, choices=KNAREA, default='A')

	def __str__(self):
		return("{}".format(self.name))

team_finder/tinder/forms.py
from django import forms
from django.core.exceptions import ValidationError
from accounts.models import Profile

from .models import Group, SkillLevel, Skill
from .fields import ReadOnlySelect


class GroupForm(forms.ModelForm):
	password2 = forms.CharField(
		widget=forms.PasswordInput,
		label='Repita a senha',
		required=False,
	)

	class Meta:
		model = Group
		fields = ('name', 'private', 'password')
		labels = {
			'name': 'Nome',
			'private': 'Privado?',
			'password': 'Senha',
		}
		widgets = {
			'password': forms.PasswordInput
		}

	def clean(self):
		cleaned_data = super(GroupForm, self).clean()

		password = cleaned_data['password']
		password2 = cleaned_data['password2']
		private = cleaned_data['private']

		if password != password2:
			self.add_error('password', ValidationError('As senhas devem ser iguais'))

		if private and not password:
			self.add_error('password', ValidationError('Grupos privados devem ter senhas'))

		if not private:
			del cleaned_data['password']


class SkillLevelForm(forms.ModelForm):
	class Meta:
		model = SkillLevel
		fields = ('skill', 'level')

	def __init__(self, *args, **kwargs):
		super(SkillLevelForm, self).__init__(*args, **kwargs)
		self.fields['skill'].disabled = True


def get_skill_level_formset():
	return forms.inlineformset_factory(
		Profile,
		SkillLevel,
		form=SkillLevelForm,
		extra=0,
		max_num=len(SkillLevel.objects.all()),
		can_delete=False,
	)


class PasswordForm(forms.Form):
	password = forms.CharField(widget=forms.PasswordInput, label="Senha de acesso")

team_finder/tinder/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed

import json

from accounts.models import Profile
from .forms import GroupForm, PasswordForm
from .models import Group, Skill, SkillLevel



def my_menu(request):
    search_term = request.GET.get('search')
    user_profile = request.user.profile

    leading = user_profile.leading.all()
    member = user_profile.group_list.all()

    if search_term:
        leading = leading.filter(name__contains=search_term)
        member = member.filter(name__contains=search_term)

    return render(request, 'tinder/main_menu.html', {'leading': leading, 'member': member})


@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.leader = request.user.profile
            group.save()
            messages.success(request, "GRUPO SALVO COM SUCESSO")
            return redirect('tinder:main_menu')
    else:
        form = GroupForm(initial={'leader': request.user.profile})

    print('erro', form.errors)
    context = {
        'form': form,
    }

    return render(request, 'tinder/create_groups.html', context)


@login_required
def search_group(request):
    search_term = request.GET.get('search')
    groups = Group.objects.all().exclude(private=True)

    if search_term:
        groups = groups.filter(name__contains=search_term)

    context = {'groups': groups}
    return render(request, 'tinder/search_group.html', context)


@login_required
def search_person(request, parameter, term):
    results = Profile.objects.filter(**{str(parameter): term})
    context = {'results': results}
    return render(request, 'core/home.html', context)


# não abrir a jaula!
@login_required  # precisa proteger p/ usuario não acessar grupos que não faz parte
def match_withlist(request, group_id):
    skills = json.loads(request.GET.get('skills'))
    skills = {int(k): int(v) for k, v in skills.items()}

    profile_skills_levels = request.user.profile.skilllevel_set.all()

    for skill_level in profile_skills_levels:
        skill = skill_level.skill
        level = skill_level.level
        if skill.id in skills and level >= skills[skill.id]:
            del skills[skill.id]

    group = Group.objects.get(id=group_id)
    members = list(group.members.exclude(id=request.user.profile.id))
    for member in members:
        member.points = 0

    for member in members:
        for skill_level in member.skilllevel_set.all():
            skill = skill_level.skill
            level = skill_level.level
            if (skill.id in skills and level >= skills[skill.id]):
                member.points += level - skills[skill.id] + 10

    best_groups = sorted(members, key=lambda x: x.points, reverse=True)

    return render(request, 'tinder/group_matches.html', {'best_groups': best_groups, 'group': group})


@login_required
def edit_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    if group.leader == request.user.profile:
        if request.method == 'POST':
            form = GroupForm(request.POST, instance=group)
            if form.is_valid():
                form.save()
                return redirect('tinder:main_menu')
        else:
            form = GroupForm(instance=group)
    else:
        return HttpResponseNotAllowed()

    return render(request, 'tinder/create_groups.html', {'form': form})


""" USERS relations inside groups """
@login_required
def join_group(request, group_id):
    group = get_object_or_404(Group, pk=group_id)
    access = False
    if request.method == 'POST':
        if group.private:
            form = PasswordForm(request.POST)
            if form.is_valid():
                userpass = form.cleaned_data['password']
                if userpass == group.password:
                    access = True
        else:
            access = True

        if access:
            group.members.add(request.user.profile)
            messages.success(request, 'Bem-vindo ao grupo')
            return redirect('tinder:detail_group', pk=group_id)
        else:
            messages.error(request, 'Informe a senha correta para acessar o grupo')
    # Form is only used if the group is private (verified in template)
    return render(request, 'tinder/join_confirmation.html', {'form': PasswordForm(), 'group': group})
@login_required
def rmv_fromgroup(request, group_id, userpass, member):
    # tirar algm de um grupo ou a si mesmo
    message = ''
    group = get_object_or_404(Group, pk=group_id)
    if (user.profile == group.leader) and (userpass == group.passwd) and (member in group.members):
        group.members.delete(member)
        message = 'REMOÇÃO BEM-SUCEDIDA.'
    else:
        message = 'IMPOSSÍVEL REALIZAR A OPERAÇÃO SOLICITADA'

    context = {'message': message}
    return render(request, 'core/home.html', context)


class DetailGroup(DetailView):
    model = Group


def activity_group_match(request, pk):
    group = get_object_or_404(Group, id=pk)
    skills = Skill.objects.all()
    levels = SkillLevel.SKLEVEL
    return render(request, 'tinder/activity.html', {'group': group, 'skills': skills, 'levels': levels})


class DeleteGroup(UserPassesTestMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('tinder:main_menu')
    success_message = 'Grupo deletado!'

    def test_func(self):
        if self.get_object().leader != self.request.user.profile:
            return False
        return True

    def delete(self, request, *args, **kwargs):
        messages.success(request, self.success_message)
        return super(DeleteGroup, self).delete(request, *args, **kwargs)

team_finder/tinder/templates/tinder/activity.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" href="{% static 'tinder/css/review.css' %}">
    <link rel="stylesheet" href="{% static 'tinder/css/activity.css' %}">
    <script>
        const skills = [{% for skill in skills %}{name:"{{ skill.name }}", value:{{ skill.id }}},{% endfor %}];
        const levels = [{% for level in levels %}{name:"{{ level.1 }}", value:{{ level.0 }}},{% endfor %}];
    </script>
{% endblock %}

{% block main_content %}
    <h2>Escolha as habilidades necessárias para realizar a tarefa!</h2>
    <div class="classes">
        <table>
            <thead>
                <tr>
                    <th>Habilidade</th>
                    <th>Nível</th>
                </tr>
            </thead>
            <tbody>
            </tbody>
            <tfoot>
                <tr>
                    <td id="add"><i class="material-icons">add</i>Adicionar Habilidade</td>
                </tr>
            </tfoot>
        </table>
        <form action="{% url 'tinder:match' group.id %}">
            <input type="text" name="skills" hidden>
            <button>Buscar</button>
        </form>
    </div>
{% endblock %}

{% block end_scripts %}
    <script>
        $("#add").click(() => {
           $('tbody').append($(`
                <tr>
                    <td>
                        <select name='skill'>
                            ${skills.map(item => `<option value=${item.value}>${item.name}</option>`)}
                        </select>
                    </td>
                    <td>
                        <select name='level'>
                            ${levels.map(item => `<option value=${item.value}>${item.name}</option>`)}
                        </select>
                    </td>
                </tr>
           `));
        });

        $('form button').click((event) => {
            event.preventDefault();
            const skills = {};
            $('tbody tr').map((idx, item) => {
                const skill = $(item).find('select[name="skill"]');
                const level = $(item).find('select[name="level"]');

                skills[skill.val()] = level.val();
            });
            $('input[name="skills"]').val(JSON.stringify(skills));
            $('form').submit();
        });

        $(() => $("#add").click())
    </script>
{% endblock %}

team_finder/tinder/templates/tinder/create_groups.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" href="{% static 'tinder/css/group_creation.css' %}">
{% endblock %}

{% block main_content %}
    <div class="group-creation">
        <h2>Criação de grupo</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.leader }}
            {{form.name.label_tag}}
            <span class="error">{{ form.name.errors }}</span>
            {{ form.name }}

            <label for="id_private" class="private-box">
                {{ form.private }}
                Privado?
            </label>

            <div id="password-box" hidden>
                {{ form.password.label_tag }}
                {{ form.password }}

                {{ form.password2.label_tag }}
                {{ form.password2 }}
            </div>

            <button>Criar grupo</button>
        </form>
    </div>
{% endblock %}

{% block end_scripts %}
    <script src="{% static 'tinder/js/group-creation.js' %}"></script>
{% endblock %}

team_finder/tinder/templates/tinder/group_confirm_delete.html
{% extends 'core/base.html' %}

{% block main_content %}
    <h2>Deletar grupo</h2>
    <form method="POST">
        {% csrf_token %}
        <p>Tem certeza que deseja deletar o grupo <strong>{{ object.name }}</strong>?</p>
        <button>Sim</button>
    </form>
{% endblock %}

team_finder/tinder/templates/tinder/group_detail.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" href="{% static 'tinder/css/review.css' %}">
{% endblock %}

{% block main_content %}
    <h2>{{ group.name }}</h2>
    Líder: {{ group.leader }}<br>
    Número de membros: {{ group.get_number_of_members }}<br>
    Fundação: {{ group.foundation }}
    <br>
    <br>
    <div class="classes">
        <div class="heading">

            <div class="menus">
                {% if user.profile in group.members.all or user.profile == group.leader %}
                    <a href="{% url 'tinder:activity-group' group.id %}"><i class="material-icons">ballot</i>Buscar duplas</a>
                {% else %}
                    <a href="{% url 'tinder:join_group' group.id%}"><i class="material-icons">person_add</i>Juntar-se no grupo</a>
                {% endif %}
            </div>
            <div class="messages">
                {% if messages %}
                    {% for message in messages %}
                        <span class="tag {{ message.tags }}">{{ message }}</span>
                    {% endfor %}
                {% endif %}
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Integrantes</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ group.leader }} (Líder)</td>
                </tr>
                {% for member in group.members.all %}
                    <tr>
                        <td>{{ member }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

team_finder/tinder/templates/tinder/group_matches.html
{% extends 'core/base.html' %}
{% load static %}

{% block head_extra %}
    <link rel="stylesheet" href="{% static 'tinder/css/review.css' %}">
{% endblock %}

{% block main_content %}
    <h2>Melhores duplas no grupo {{ group.name }}</h2>

    <div class="classes">
        <table>
            <thead>
                <tr>
                    <td>Dupla</td>
                    <td>Pontuação</td>
                </tr>
            </thead>
            <tbody>
                {% for best_group in best_groups %}
                    <tr>
                        <td>{{ best_group }}</td>
                        <td>{{ best_group.points }}</td>
                    </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}

team_finder/tinder/templates/tinder/join_confirmation.html
{% extends 'core/base.html' %}

{% block main_content %}
    <h1>Entrar no grupo {{ group.name }}?</h1>
    {% if messages %}
        {% for message in messages %}
            <span class="{{ message.tags }} tag">{{ message }}</span>
        {% endfor %}
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {% if group.private %}
            {{ form.as_p }}
        {% endif %}
        <button>Entrar</button>
    </form>
{% endblock %}

team_finder/tinder/templates/tinder/main_menu.html
{% extends 'core/base.html' %}

{% load static %}

{% block head_extra %}
    <link rel="stylesheet" href="{% static 'tinder/css/review.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.5/cropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.5/cropper.min.js"></script>
{% endblock head_extra %}

{% block main_content %}
    <div class="profile-container">
        <div class="profile-content">
            <div class="info">
                <div class="heading">
                    <h2>Perfil</h2>
                    <a class="edit-btn" href="{% url 'edit_profile' %}">Editar</a>
                </div>
                <img src="{{ user.profile.avatar.url }}" alt="">
                <p>{{ user.first_name }}</p>
                <p>{{ user.profile.shortbio }}</p>
            </div>
            <div class="classes">
                <div class="heading">
                    <h2>Meus grupos</h2>
                    <div class="menus">
                        <a href="{% url 'tinder:create_group' %}"><i class="material-icons">add</i>Criar Grupo</a>
                        <form class="search-form default">
                            <input type="text" class="group-search" placeholder="Pesquisa por grupos..." name="search">
                            <button><i class="material-icons">search</i></button>
                        </form>
                    </div>
                </div>
                <div class="messages">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endif %}
                </div>
                <table>
                    <thead>
                        <tr>
                            <th>Grupo</th>
                            <th>Líder</th>
                            <th>Número de membros</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if leading or member %}
                            {% for group in leading %}
                                <tr>
                                    <td>{{group.name}}</td>
                                    <td>{{group.leader}}</td>
                                    <td>{{group.get_number_of_members}}</td>
                                    <td>
                                        <a href="{% url 'tinder:detail_group' group.id %}"><i class="material-icons">visibility</i></a>
                                        {% if group.leader == user.profile %}
                                            <a href="{% url 'tinder:edit_group' group.id%}"><i class="material-icons">edit</i></a>
                                            <a href="{% url 'tinder:delete_group' group.id%}"><i class="material-icons">delete</i></a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            {% for group in member %}
                                <tr>
                                    <td>{{ group.name }}</td>
                                    <td>{{ group.leader }}</td>
                                    <td>{{ group.get_number_of_members}}</td>
                                    <td>
                                        {% if group.leader == user.profile %}
                                            <a href="{% url 'tinder:edit_group' group.id%}"><i class="material-icons">edit</i></a>
                                        {% endif %}
                                        <a href="{% url 'tinder:detail_group' group.id%}"><i class="material-icons">visibility</i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td>Não há nenhum grupo para mostar😢<br>Mas você pode criá-lo!</td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

team_finder/tinder/templates/tinder/search_group.html
{% extends 'core/base.html' %}

{% load static %}

{% block head_extra %}
	<link rel="stylesheet" href="{% static 'tinder/css/review.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.5/cropper.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.5/cropper.min.js"></script>
{% endblock head_extra %}

{% block main_content %}
	<div class="classes">
        <div class="heading">
            <h2>Resultados da busca</h2>
            <div class="menus">
                <a href="{% url 'tinder:create_group' %}"><i class="material-icons">add</i>Criar Grupo</a>
                <form class="search-form default">
                    <input type="text" class="group-search" placeholder="Pesquisa por grupos..." name="search">
                    <button><i class="material-icons">search</i></button>
                </form>
            </div>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Grupo</th>
                    <th>Líder</th>
                    <th>Número de membros</th>
                    <th>Acessar</th>
                </tr>
            </thead>
            <tbody>
                {% if groups %}
                    {% for group in groups %}
                        <tr>
                            <td>{{group.name}}</td>
                            <td>{{group.leader}}</td>
                            <td>{{group.get_number_of_members}}</td>
                            <td>
                                <a href="{% url 'tinder:detail_group' group.id %}"><i class="material-icons">visibility</i></a>
                                {% if group.leader == user.profile %}
                                    <a href="{% url 'tinder:edit_group' group.id%}"><i class="material-icons">edit</i></a>
                                    <a href="{% url 'tinder:delete_group' group.id%}"><i class="material-icons">delete</i></a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>Não há nenhum grupo para mostar😢<br>Mas você pode criá-lo!</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
{% endblock main_content %}